### ISSUE TITLE
Search engine suggestions stay visible

### ISSUE THREAD

**Issue by sushiprod** [la-trace/website#5]
Try a search using the map search input until active a city suggestion
do not valide the search
click on a track
=> Suggestions in the search input stay visbile

Try a new search
=> tracks are gone, zoom map are inactive
=> page must be reloaded
![capture d ecran 2018-04-02 a 09 41 50](https://user-images.githubusercontent.com/6919171/38188021-4cb459d0-365a-11e8-9002-2b45e3df2957.png)

osX chrome 63

**Comment by alexjomin** [comment]
moved to team discussion
